steps:
  - id: "running tests"
    name: "gcr.io/cloud-builders/go"
    args: ["test", "."]
    env: ["GOPATH=."]

  - id: "Building image from Dockerfile.prod"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/go-hpa:$SHORT_SHA",
        "-f",
        "Dockerfile.prod",
        ".",
      ]

  - id: "Pushing image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/go-hpa:$SHORT_SHA"]

  - id: "adjusting k8s deployment file"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "/bin/sh"
    args:
      - "-c"
      - |
        sed 's#img-app-deployment#gcr.io/$PROJECT_ID/go-hpa:$SHORT_SHA#g' k8s/deployment.yaml > k8s/deployment-new.yaml;
        cat k8s/deployment-new.yaml;

  - id: "Deploying k8s"
    name: "gcr.io/cloud-builders/kubectl"
    args:
      - "apply"
      - "-f"
      - "k8s/deployment-new.yaml"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=go-hpa"

  - id: "Deploying requester pod"
    name: "gcr.io/cloud-builders/kubectl"
    args:
      - "apply"
      - "-f"
      - "k8s/requester-pod.yaml"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=go-hpa"
