apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hpa
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: go-hpa
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-hpa
    spec:
      containers:
        - name: go-hpa
          image: img-app-deployment
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
            limits:
              cpu: "100m"
---

apiVersion: v1
kind: Service
metadata:
  name: go-hpa
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app.kubernetes.io/name: go-hpa

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-hpa
spec:
  maxReplicas: 6
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-hpa
  targetCPUUtilizationPercentage: 15
