apiVersion: v1
kind: Pod
metadata:
  name: requester
spec:
  containers:
    - name: requester
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        [
          "while true ; do wget -q -O- http://go-hpa.default.svc.cluster.local; done;",
        ]
